### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by renk100** [Lemonzhulixin/monkeyTest#1]
E:\PythonProject\First\venv\Scripts\python.exe E:/PythonProject/monkeyTest-master/Monkey_performance/monkeyTest.py
持久性目录info已存在，继续执行测试!
当前已连接待测手机数为：1
1
创建持久性文件...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "E:/PythonProject/monkeyTest-master/Monkey_performance/monkeyTest.py", line 215, in run
    start(self.dev)
  File "E:/PythonProject/monkeyTest-master/Monkey_performance/monkeyTest.py", line 67, in start
    Create_pickle(dev, app, num)
  File "E:/PythonProject/monkeyTest-master/Monkey_performance/monkeyTest.py", line 53, in Create_pickle
    OperateFile(cpu).mkdir_file()
  File "E:\PythonProject\monkeyTest-master\Monkey_performance\Base\BaseFile.py", line 46, in mkdir_file
    f = open(self.file, self.method)
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\PythonProject\\monkeyTest-master\\Monkey_performance\\info\\emulator-5554_cpu.pickle'

**Comment by Testlyy** [comment]
我也存在上面问题，提示线程冲突

**Comment by Testlyy** [comment]
可以帮忙解决一下吗？但是我有一次不知道为什么执行成功

**Comment by shijiaojiao123** [comment]
我也存在这个问题，一次都没执行成功过
持久性目录info已存在，继续执行测试!
当前已连接待测手机数为：1
1
创建持久性文件...
pix---  720x1280
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/shijiaojiao/Documents/work/monkeyTest/monkeyTest.py", line 218, in run
    start(self.dev)
  File "/Users/shijiaojiao/Documents/work/monkeyTest/monkeyTest.py", line 70, in start
    Create_pickle(dev, app, num)
  File "/Users/shijiaojiao/Documents/work/monkeyTest/monkeyTest.py", line 54, in Create_pickle
    app[dev] = {"cpu": cpu, "men": men, "flow": flow, "battery": battery, "fps": fps, "header": get_phone(dev)}
  File "/Users/shijiaojiao/Documents/work/monkeyTest/monkeyTest.py", line 25, in get_phone
    phone_info = BasePhoneMsg.get_phone_Kernel(dev)
  File "/Users/shijiaojiao/Documents/work/monkeyTest/Base/BasePhoneMsg.py", line 56, in get_phone_Kernel
    men_total = get_men_total(dev)
  File "/Users/shijiaojiao/Documents/work/monkeyTest/Base/BasePhoneMsg.py", line 21, in get_men_total
    output = subprocess.check_output(cmd).split()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'adb -s 54f190fc shell cat /proc/meminfo'

**Comment by sungj521** [comment]
我是提示 设备不存在，但是我的无线已经链接上了
这个咋破？
